from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status

# Create your views here.

Ccurrency={'Afghanistan': {'capital': 'Kabul', 'currency': 'Afghani'},
 'Albania': {'capital': 'Tirane', 'currency': 'Lek'},
 'Algeria': {'capital': 'Algiers', 'currency': 'Dinar'},
 'Andorra': {'capital': 'Andorra la Vella', 'currency': 'Euro'},
 'Angola': {'capital': 'Luanda', 'currency': 'New Kwanza'},
 'Antigua and Barbuda': {'capital': 'Saint John’s',
  'currency': 'East Caribbean dollar'},
 'Argentina': {'capital': 'Buenos Aires', 'currency': 'Peso'},
 'Armenia': {'capital': 'Yerevan', 'currency': 'Dram'},
 'Australia': {'capital': 'Canberra', 'currency': 'Australian dollar'},
 'Austria': {'capital': 'Vienna', 'currency': 'Euro (formerly schilling)'},
 'Azerbaijan': {'capital': 'Baku', 'currency': 'Manat'},
 'The Bahamas': {'capital': 'Nassau', 'currency': 'Bahamian dollar'},
 'Bahrain': {'capital': 'Manama', 'currency': 'Bahrain dinar'},
 'Bangladesh': {'capital': 'Dhaka', 'currency': 'Taka'},
 'Barbados': {'capital': 'Bridgetown', 'currency': 'Barbados dollar'},
 'Belarus': {'capital': 'Minsk', 'currency': 'Belorussian ruble'},
 'Belgium': {'capital': 'Brussels',
  'currency': 'Euro (formerly Belgian franc)'},
 'Belize': {'capital': 'Belmopan', 'currency': 'Belize dollar'},
 'Benin': {'capital': 'Porto-Novo', 'currency': 'CFA Franc'},
 'Bhutan': {'capital': 'Thimphu', 'currency': 'Ngultrum'},
 'Bolivia': {'capital': 'La Paz (administrative); Sucre (judicial)',
  'currency': 'Boliviano'},
 'Bosnia and Herzegovina': {'capital': 'Sarajevo',
  'currency': 'Convertible Mark'},
 'Botswana': {'capital': 'Gaborone', 'currency': 'Pula'},
 'Brazil': {'capital': 'Brasilia', 'currency': 'Real'},
 'Brunei': {'capital': 'Bandar Seri Begawan', 'currency': 'Brunei dollar'},
 'Bulgaria': {'capital': 'Sofia', 'currency': 'Lev'},
 'Burkina Faso': {'capital': 'Ouagadougou', 'currency': 'CFA Franc'},
 'Burundi': {'capital': 'Gitega', 'currency': 'Burundi franc'},
 'Cambodia': {'capital': 'Phnom Penh', 'currency': 'Riel'},
 'Cameroon': {'capital': 'Yaounde', 'currency': 'CFA Franc'},
 'Canada': {'capital': 'Ottawa', 'currency': 'Canadian dollar'},
 'Cape Verde': {'capital': 'Praia', 'currency': 'Cape Verdean escudo'},
 'Central African Republic': {'capital': 'Bangui', 'currency': 'CFA Franc'},
 'Chad': {'capital': 'N’Djamena', 'currency': 'CFA Franc'},
 'Chile': {'capital': 'Santiago', 'currency': 'Chilean Peso'},
 'China': {'capital': 'Beijing', 'currency': 'Chinese Yuan'},
 'Colombia': {'capital': 'Bogota', 'currency': 'Colombian Peso'},
 'Comoros': {'capital': 'Moroni', 'currency': 'Franc'},
 'Republic of the Congo': {'capital': 'Brazzaville', 'currency': 'CFA Franc'},
 'Zimbabwe': {'capital': 'Harare', 'currency': 'United States dollar'},
 'Costa Rica': {'capital': 'San Jose', 'currency': 'Colón'},
 'Cote d’Ivoire': {'capital': 'Yamoussoukro (official); Abidjan (de facto)',
  'currency': 'CFA Franc'},
 'Croatia': {'capital': 'Zagreb', 'currency': 'Croatian'},
 'Cuba': {'capital': 'Havana', 'currency': 'Cuban Peso'},
 'Cyprus': {'capital': 'Nicosia', 'currency': 'Euro'},
 'Czech Republic': {'capital': 'Prague', 'currency': 'Koruna'},
 'Denmark': {'capital': 'Copenhagen', 'currency': 'Danish Krone'},
 'Djibouti': {'capital': 'Djibouti', 'currency': 'Djiboutian franc'},
 'Dominica': {'capital': 'Roseau', 'currency': 'East Caribbean dollar'},
 'Dominican Republic': {'capital': 'Santo Domingo',
  'currency': 'Dominican Peso'},
 'East Timor (Timor-Leste)': {'capital': 'Dili', 'currency': 'U.S. dollar'},
 'Ecuador': {'capital': 'Quito', 'currency': 'U.S. dollar'},
 'Egypt': {'capital': 'Cairo', 'currency': 'Egyptian pound'},
 'El Salvador': {'capital': 'San Salvador', 'currency': 'Colón; U.S. dollar'},
 'Equatorial Guinea': {'capital': 'Malabo', 'currency': 'CFA Franc'},
 'Eritrea': {'capital': 'Asmara', 'currency': 'Nakfa'},
 'Estonia': {'capital': 'Tallinn', 'currency': 'Estonia Kroon; Euro'},
 'Ethiopia': {'capital': 'Addis Ababa', 'currency': 'Birr'},
 'Fiji': {'capital': 'Suva', 'currency': 'Fiji dollar'},
 'Finland': {'capital': 'Helsinki', 'currency': 'Euro (formerly markka)'},
 'France': {'capital': 'Paris', 'currency': 'Euro (formerly French franc)'},
 'Gabon': {'capital': 'Libreville', 'currency': 'CFA Franc'},
 'The Gambia': {'capital': 'Banjul', 'currency': 'Dalasi'},
 'Georgia': {'capital': 'Tbilisi', 'currency': 'Lari'},
 'Germany': {'capital': 'Berlin', 'currency': 'Euro (formerly Deutsche mark)'},
 'Ghana': {'capital': 'Accra', 'currency': 'Cedi'},
 'Greece': {'capital': 'Athens', 'currency': 'Euro (formerly drachma)'},
 'Grenada': {'capital': 'Saint George’s', 'currency': 'East Caribbean dollar'},
 'Guatemala': {'capital': 'Guatemala City', 'currency': 'Quetzal'},
 'Guinea': {'capital': 'Conakry', 'currency': 'Guinean franc'},
 'Guinea-Bissau': {'capital': 'Bissau', 'currency': 'CFA Franc'},
 'Guyana': {'capital': 'Georgetown', 'currency': 'Guyanese dollar'},
 'Haiti': {'capital': 'Port-au-Prince', 'currency': 'Gourde'},
 'Honduras': {'capital': 'Tegucigalpa', 'currency': 'Lempira'},
 'Hungary': {'capital': 'Budapest', 'currency': 'Forint'},
 'Iceland': {'capital': 'Reykjavik', 'currency': 'Icelandic króna'},
 'India': {'capital': 'New Delhi', 'currency': 'Indian Rupee'},
 'Indonesia': {'capital': 'Jakarta', 'currency': 'Rupiah'},
 'Iran': {'capital': 'Tehran', 'currency': 'Rial'},
 'Iraq': {'capital': 'Baghdad', 'currency': 'Iraqi Dinar'},
 'Ireland': {'capital': 'Dublin',
  'currency': 'Euro (formerly Irish pound [punt])'},
 'Israel': {'capital': 'Jerusalem*', 'currency': 'Shekel'},
 'Italy': {'capital': 'Rome', 'currency': 'Euro (formerly lira)'},
 'Jamaica': {'capital': 'Kingston', 'currency': 'Jamaican dollar'},
 'Japan': {'capital': 'Tokyo', 'currency': 'Yen'},
 'Jordan': {'capital': 'Amman', 'currency': 'Jordanian dinar'},
 'Kazakhstan': {'capital': 'Nur Sultan', 'currency': 'Tenge'},
 'Kenya': {'capital': 'Nairobi', 'currency': 'Kenya shilling'},
 'Kiribati': {'capital': 'Tarawa Atoll', 'currency': 'Kiribati dollar'},
 'North Korea': {'capital': 'Pyongyang', 'currency': 'Won'},
 'South Korea': {'capital': 'Seoul', 'currency': 'Won'},
 'Kuwait': {'capital': 'Kuwait City', 'currency': 'Kuwaiti Dinar'},
 'Kyrgyzstan': {'capital': 'Bishkek', 'currency': 'Som'},
 'Laos': {'capital': 'Vientiane', 'currency': 'New Kip'},
 'Latvia': {'capital': 'Riga', 'currency': 'Lats'},
 'Lebanon': {'capital': 'Beirut', 'currency': 'Lebanese pound'},
 'Lesotho': {'capital': 'Maseru', 'currency': 'Maluti'},
 'Liberia': {'capital': 'Monrovia', 'currency': 'Liberian dollar'},
 'Libya': {'capital': 'Tripoli', 'currency': 'Libyan dinar'},
 'Liechtenstein': {'capital': 'Vaduz', 'currency': 'Swiss franc'},
 'Lithuania': {'capital': 'Vilnius', 'currency': 'Litas'},
 'Luxembourg': {'capital': 'Luxembourg',
  'currency': 'Euro (formerly Luxembourg franc)'},
 'Macedonia': {'capital': 'Skopje', 'currency': 'Denar'},
 'Madagascar': {'capital': 'Antananarivo', 'currency': 'Malagasy Ariary'},
 'Malawi': {'capital': 'Lilongwe', 'currency': 'Kwacha'},
 'Malaysia': {'capital': 'Kuala Lumpur', 'currency': 'Ringgit'},
 'Maldives': {'capital': 'Male', 'currency': 'Rufiyaa'},
 'Mali': {'capital': 'Bamako', 'currency': 'CFA Franc'},
 'Malta': {'capital': 'Valletta', 'currency': 'Euro'},
 'Marshall Islands': {'capital': 'Majuro', 'currency': 'U.S. Dollar'},
 'Mauritania': {'capital': 'Nouakchott', 'currency': 'Ouguiya'},
 'Mauritius': {'capital': 'Port Louis', 'currency': 'Mauritian rupee'},
 'Mexico': {'capital': 'Mexico City', 'currency': 'Mexican peso'},
 'Federated States of Micronesia': {'capital': 'Palikir',
  'currency': 'U.S. Dollar'},
 'Moldova': {'capital': 'Chisinau', 'currency': 'Leu'},
 'Monaco': {'capital': 'Monte Carlo', 'currency': 'Euro'},
 'Mongolia': {'capital': 'Ulaanbaatar', 'currency': 'Togrog'},
 'Montenegro': {'capital': 'Podgorica', 'currency': 'Euro'},
 'Morocco': {'capital': 'Rabat', 'currency': 'Dirham'},
 'Mozambique': {'capital': 'Maputo', 'currency': 'Metical'},
 'Myanmar (Burma)': {'capital': 'Nay Pyi Taw', 'currency': 'Kyat'},
 'Namibia': {'capital': 'Windhoek', 'currency': 'Namibian dollar'},
 'Nauru': {'capital': 'no official capital; government offices in Yaren District',
  'currency': 'Australian dollar'},
 'Nepal': {'capital': 'Kathmandu', 'currency': 'Nepalese rupee'},
 'Netherlands': {'capital': 'Amsterdam; The Hague (seat of government)',
  'currency': 'Euro (formerly guilder)'},
 'New Zealand': {'capital': 'Wellington', 'currency': 'New Zealand dollar'},
 'Nicaragua': {'capital': 'Managua', 'currency': 'Gold cordoba'},
 'Niger': {'capital': 'Niamey', 'currency': 'CFA Franc'},
 'Nigeria': {'capital': 'Abuja', 'currency': 'Naira'},
 'Norway': {'capital': 'Oslo', 'currency': 'Norwegian krone'},
 'Oman': {'capital': 'Muscat', 'currency': 'Omani rial'},
 'Pakistan': {'capital': 'Islamabad', 'currency': 'Pakistani rupee'},
 'Palau': {'capital': 'Melekeok', 'currency': 'U.S. dollar'},
 'Palestine': {'capital': 'Ramallah, East Jerusalem',
  'currency': 'Palestine Pound'},
 'Panama': {'capital': 'Panama City', 'currency': 'Balboa; U.S. dollar'},
 'Papua New Guinea': {'capital': 'Port Moresby', 'currency': 'Kina'},
 'Paraguay': {'capital': 'Asuncion', 'currency': 'Guaraní'},
 'Peru': {'capital': 'Lima', 'currency': 'Nuevo sol (1991)'},
 'Philippines': {'capital': 'Manila', 'currency': 'Peso'},
 'Poland': {'capital': 'Warsaw', 'currency': 'Zloty'},
 'Portugal': {'capital': 'Lisbon', 'currency': 'Euro (formerly escudo)'},
 'Qatar': {'capital': 'Doha', 'currency': 'Qatari riyal'},
 'Romania': {'capital': 'Bucharest', 'currency': 'Romanian Rupee'},
 'Russia': {'capital': 'Moscow', 'currency': 'Ruble'},
 'Rwanda': {'capital': 'Kigali', 'currency': 'Rwandan franc'},
 'Saint Kitts and Nevis': {'capital': 'Basseterre',
  'currency': 'East Caribbean dollar'},
 'Saint Lucia': {'capital': 'Castries', 'currency': 'East Caribbean dollar'},
 'Saint Vincent and the Grenadines': {'capital': 'Kingstown',
  'currency': 'East Caribbean dollar'},
 'Samoa': {'capital': 'Apia', 'currency': 'Tala'},
 'San Marino': {'capital': 'San Marino', 'currency': 'Euro'},
 'Sao Tome and Principe': {'capital': 'Sao Tome', 'currency': 'Dobra'},
 'Saudi Arabia': {'capital': 'Riyadh', 'currency': 'Riyal'},
 'Senegal': {'capital': 'Dakar', 'currency': 'CFA Franc'},
 'Serbia': {'capital': 'Belgrade', 'currency': 'Serbian Dinar'},
 'Seychelles': {'capital': 'Victoria', 'currency': 'Seychelles rupee'},
 'Sierra Leone': {'capital': 'Freetown', 'currency': 'Leone'},
 'Singapore': {'capital': 'Singapore', 'currency': 'Singapore dollar'},
 'Slovakia': {'capital': 'Bratislava', 'currency': 'Euro'},
 'Slovenia': {'capital': 'Ljubljana',
  'currency': 'Slovenian tolar; euro (as of 1/1/07)'},
 'Solomon Islands': {'capital': 'Honiara',
  'currency': 'Solomon Islands dollar'},
 'Somalia': {'capital': 'Mogadishu', 'currency': 'Somali shilling'},
 'South Africa': {'capital': 'Pretoria (administrative); Cape Town (legislative); Bloemfontein (judiciary)',
  'currency': 'Rand'},
 'South Sudan': {'capital': 'Juba', 'currency': 'Sudanese Pound'},
 'Spain': {'capital': 'Madrid', 'currency': 'Euro (formerly peseta)'},
 'Sri Lanka': {'capital': 'Colombo; Sri Jayewardenepura Kotte (legislative)',
  'currency': 'Sri Lankan rupee'},
 'Sudan': {'capital': 'Khartoum', 'currency': 'Sudanese Pound'},
 'Suriname': {'capital': 'Paramaribo', 'currency': 'Surinamese dollar'},
 'Swaziland': {'capital': 'Mbabane', 'currency': 'Lilangeni'},
 'Sweden': {'capital': 'Stockholm', 'currency': 'Krona'},
 'Switzerland': {'capital': 'Berne', 'currency': 'Swiss franc'},
 'Syria': {'capital': 'Damascus', 'currency': 'Syrian pound'},
 'Taiwan': {'capital': 'Taipei', 'currency': 'Taiwan dollar'},
 'Tajikistan': {'capital': 'Dushanbe', 'currency': 'somoni'},
 'Tanzania': {'capital': 'Dar es Salaam; Dodoma (legislative)',
  'currency': 'Tanzanian shilling'},
 'Thailand': {'capital': 'Bangkok', 'currency': 'Baht'},
 'Togo': {'capital': 'Lome', 'currency': 'CFA Franc'},
 'Tonga': {'capital': 'Nuku’alofa', 'currency': 'Pa’anga'},
 'Trinidad and Tobago': {'capital': 'Port-of-Spain',
  'currency': 'Trinidad and Tobago dollar'},
 'Tunisia': {'capital': 'Tunis', 'currency': 'Tunisian dinar'},
 'Turkey': {'capital': 'Ankara', 'currency': 'Turkish lira (YTL)'},
 'Turkmenistan': {'capital': 'Ashgabat', 'currency': 'Manat'},
 'Tuvalu': {'capital': 'Vaiaku village, Funafuti province',
  'currency': 'Tuvaluan Dollar'},
 'Uganda': {'capital': 'Kampala', 'currency': 'Ugandan new shilling'},
 'Ukraine': {'capital': 'Kiev', 'currency': 'Hryvnia'},
 'United Arab Emirates': {'capital': 'Abu Dhabi', 'currency': 'U.A.E. Dirham'},
 'United Kingdom': {'capital': 'London', 'currency': 'Pound sterling'},
 'United States of America': {'capital': 'Washington D.C.',
  'currency': 'Dollar'},
 'Uruguay': {'capital': 'Montevideo', 'currency': 'Uruguay peso'},
 'Uzbekistan': {'capital': 'Tashkent', 'currency': 'Uzbekistani sum'},
 'Vanuatu': {'capital': 'Port-Vila', 'currency': 'Vatu'},
 'Vatican City (Holy See)': {'capital': 'Vatican City', 'currency': 'Euro'},
 'Venezuela': {'capital': 'Caracas', 'currency': 'Bolivar'},
 'Vietnam': {'capital': 'Hanoi', 'currency': 'Dong'},
 'Yemen': {'capital': 'Sanaa', 'currency': 'Rial'},
 'Zambia': {'capital': 'Lusaka', 'currency': 'kwacha'}
 }


class Currency_Converter(APIView):
    def get(self,price,fromcnt,tocnt):
        pass;

class CountryCurrency(APIView):
    def get(self,request, country=None):
        if country==None:
            #print all the data of currency of different countries.
            country=Ccurrency;
        else:
            country=country.capitalize().replace(' ','');
            print(country)
            flag=0;
            for keys, values in Ccurrency.items():
                if keys.replace(' ','').capitalize() == country:
                    country=Ccurrency[keys];
                    flag=1;
                    break;
            if flag!=1:

                return Response({'Msg':'Please Enter A Valid Country Name'}, status=status.HTTP_404_NOT_FOUND);
        return Response(country,status=status.HTTP_202_ACCEPTED)

        
