# Generated by Django 4.0.4 on 2023-03-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('crushName', models.CharField(max_length=100)),
                ('PhoneNo', models.IntegerField(unique=True, verbose_name='no')),
            ],
        ),
    ]
