# Generated by Django 4.0.4 on 2023-03-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='crushName',
            new_name='crush',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='PhoneNo',
            new_name='phone',
        ),
    ]
